name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{ github.event.pull_request.title }}"
      - name: Print PR Lables
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.lables) }}
          EOF
      - name: Bug step
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
        run: echo "I am a bug fix"
      - name: Sleep for 20 sec
        run: sleep 5
      - name: "Failing step"
        run: exit 1
      
      - name: I will be skipped
        if: ${{ success() }}
        run: |
          echo "I will print if previous steps succeed."
      
      - name: I will execute
        if: ${{ failure() }}
        run: |
          echo "I will execute"
      
      - name: I will exectue
        if: ${{ !cancelled() }}
        run: |
          echo "I will always print, except when the workflow is cacelled"
      
      - name: I will exectue when cancelled
        if: ${{ cancelled() }}
        run: |
          echo "I will print, if workflow has been cancelled"



      
