name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.Build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: Build
        run: echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
      
      - name: Print GITHUB_OUTPUT Again
        run: echo $GITHUB_OUTPUT