name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: |
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
          echo "myname=sushant" >> $GITHUB_OUTPUT
          echo "city=Jaysingpur" >> $GITHUB_OUTPUT
          echo "year=2024" >> $GITHUB_OUTPUT
      - name: Checking the GITHUB_OUTPUT
        run: |
          cat "$GITHUB_OUTPUT"
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        if: ${{ needs.build.outputs.build-status == 'success'}}
        run: echo "Deploying"
      - name: Cat github oputput
        run: |
          cat "$GITHUB_OUTPUT"
      