name: 18.2 - Reusable Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github.workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: temp-dir
  print-output:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status}}"
          echo "URL: ${{ needs.deploy.outputs.url }}"